//
//  Storage.swift
//  SAT Vocabulary
//
//  Created by Askar Almukhamet on 27.02.2022.
//

import Foundation

struct Storage {
    static var words = [
        "sought",
        "discern",
        "inexplicable",
        "lethargic",
        "tranquil",
        "viscous",
        "serene",
        "resilient",
        "to ring",
        "overlook",
        "feasible",
        "prompt",
        "incentice",
        "elaborate",
        "amiable",
        "ambivalent",
        
        "anticipation",
        "reticence",
        "apprehension",
        "contemplation",
        "diffidence",
        "disposition",
        "commemorates",
        
        "despise - scorn - contempt",
        "Unwavering - steadfast",
        "Humongous - colossal",
        "Egotist - boaster",
        "Futile - pointless",
        "Impending - about to happen",
        "Illicit - illegal",
        "Elude - fail to be grasped",
        "Eke - scrape by",
        "Conducive - helpful",
        "Cohesive - United",
        "Entice - tempt",
        "Irk - annoy",
        "Docile - easily managed",
        "Summit - highest point - acme  - apex",
        "Buck - resist",
        "Avert - prevent",
        "Amply - fully",
        "Dupe - swindle - deceived",
        "Candid - straightforward",
        "Augment - increase",
        "Bleak - hopeless",
        "Unnerve - make one lose confidence",
        "Avid - enthusiastic",
        "Sporadic - occasional",
        "Secular - non-religious",
        
        "abstruse",
        "apt",
        "cajole",
        "compendious",
        "concur",
        "delineate",
        "digress(ion)",
        "elucidate",
        "embroil(ed)",
        "empiric(al)",
        "enumerate",
        "epitome, epitomize",
        "equivocal",
        "exemplar",
        "exhort",
        "expedient",
        "fathom (verb)",
        "flagrant",
        "florid(ity)",
        "incongruity, incongruous",
        "ineffable",
        "innuendo",
        "laconic",
        "lucid",
        "nebulous",
        "nuance",
        "paradigm",
        "prattle",
        "pronouncement",
        "proponent",
        "prosaic",
        
        "rebuttal",
        "recant",
        "repudiate",
        "rescind",
        "rhetoric(al), rhetorician",
        "scrutinize, scrutiny",
        "simile",
        "tangential",
        "treatise",
        "verbose",
        "aura",
        "bombastic",
        "buoyant",
        "callous",
        "cantankerous(ness)",
        "capricious",
        "caustic",
        "convivial",
        "demonstrative",
        "despondent",
        "diffident, diffidence",
        "discomfited",
        "disillusionment",
        "dispassionate",
        "elated, elation",
        "evoke",
        "felicitous",
        "forlorn",
        "fortitude",
        "furor",
        "histrionic",
        "idyllic",
        "impetuous",
        "irate",
        "jaded",
        "jocular",
        "jovial",
        "maudlin",
        "melancholy",
        "mercurial",
        "morose",
        "peevish",
        "penchant",
        "perfunctory",
        "petulant",
        
        "profound, profundity",
        "propensity",
        "repugnant",
        "reticent, reticence",
        "sanguine",
        "solace",
        "somber",
        "temperamental",
        "trepidation",
        "truculent, truculence",
        "vicarious",
        "wrath",
        "alacrity",
        "dormant",
        "ebullient",
        "equanimity",
        "hardy",
        "indolent",
        "insipid",
        "instigate",
        "invoke",
        "lackadaisical",
        "laggard",
        "languid",
        "listless",
        "lull",
        "pacify",
        "placate",
        "placid",
        "raucous",
        "rouse, rousing",
        "scintillating",
        "stagnant, stagnation",
        "static (adjective)",
        "torpor",
        "unruly",
        "vapid",
        "abhor, abhorrence",
        "acrimony",
        "amicable",
        "antipathy",
        "congenial",
        "disputatious",
        
        "estrange, estrangement",
        "exacting",
        "genial",
        "officious",
        "rancor(ous)",
        "rapport",
        "recluse, reclusive",
        "solicitous(ness)",
        "unwitting",
        "amenable",
        "aspire",
        "assiduous",
        "assuage",
        "compliant, compliance",
        "dauntless",
        "debacle",
        "debilitate(d)",
        "deference, deferential",
        "deterrent",
        "disheartening",
        "dispel",
        "disquiet(ing)",
        "facile",
        "futile, futility",
        "gallant(ry)",
        "impasse",
        "indomitable",
        "intrepid",
        "onerous",
        "servile",
        "steadfast",
        "subservient",
        "tenacious, tenacity",
        "tenuous",
        "tribulation",
        "vying",
        "acumen",
        
        "adept",
        "adroit",
        "anthropology",
        "boorish, boorishness",
        "cerebral",
        "churlish",
        "conscientious",
        "cosmopolitan",
        "credulity, credulous",
        "didactic",
        "discern, discerning",
        "epiphany",
        "erudite, erudition",
        "esoteric",
        "fastidious",
        "finesse",
        "flummox",
        "folly",
        "foolhardy",
        "grandiose",
        "inane",
        "ineptitude",
        "ingenuous",
        "lithe",
        "neophyte",
        "oversight",
        "painstaking",
        "pedant, pedantic, pedantry",
        "precocious",
        "provincial",
        "punctilious",
        "pundit",
        "quixotic",
        "sage",
        "scrupulous",
        "shrewd",
        "slipshod",
        "stupefy, stupefaction",
        "susceptible",
        "tractable",
        "uncanny",
        "uncouth",
        "unfathomable",
        
        "ungainly",
        "urbane",
        "venerable",
        "virtuoso, virtuosity",
        "wry",
        "corroborate",
        "decorum, decorous",
        "equitable",
        "illicit",
        "incriminate",
        "indict(ment)",
        "indignant",
        "indulgent",
        "judicious",
        "ratify",
        "sanction (verb)",
        "vindicate, vindication",
        "altruistic, altruism",
        "avarice",
        "benevolent",
        "bequeath",
        "depreciation, depreciatory",
        "destitute",
        "exorbitant",
        "frugal(ity)",
        "lucrative",
        "luxuriant",
        "magnanimity, magnanimous",
        "mercenary",
        "miserly",
        "patronize",
        "penurious",
        "perquisite",
        "procure",
        "provident",
        "squander",
        "venal(ity)",
        "vocation",
        "aberration",
        "accost",
        
        "adamant",
        "ascendancy",
        "ascetic, asceticism",
        "august",
        "autocrat, autocratic",
        "automaton",
        "banal",
        "bipartisanship",
        "depose",
        "derivative",
        "desecration",
        "despot",
        "doctrine",
        "dogmatic",
        "eclectic",
        "egalitarian",
        "exhibitionist, exhibitionistic",
        "faction",
        "fanaticism",
        "hackneyed",
        "heresy, heretic",
        "idiosyncracy, idiosyncratic",
        "orthodox",
        "pacifist",
        "partisan",
        "piety, pious",
        "polemical",
        "renounce",
        "reverent",
        "sanctity",
        "staunch",
        "stock (adjective)",
        "strident",
        "subversive",
        "supplant",
        "sycophant",
        "toady",
        "totalitarian",
        
        "trite",
        "usurp",
        "zealot",
        "assail",
        "berate",
        "castigate",
        "censorious",
        "censure",
        "chastise",
        "chide",
        "consternation",
        "contempt(uous)",
        "contemptible",
        "culpable",
        "denigrate",
        "deprecate",
        "deride",
        "discount (verb)",
        "disparage",
        "eulogy, eulogize",
        "extol",
        "laud, laudatory",
        "noxious",
        "reprehensible",
        "reprimand",
        "reproach",
        "scathing",
        "slight (verb)",
        "spurn",
        "tirade",
        "tout",
        "affected",
        "chagrin",
        "complacency, complacent",
        "conciliate, conciliatory",
        "degradation",
        "demure, demurral",
        "flippant, flippancy",
        "hubris",
        "ignominy, ignominious",
        "imperious",
        "impudence, impudent",
        
        "insolence, insolent",
        "irreverent, irreverence",
        "notoriety, notorious",
        "obdurate",
        "obstinate, -acy",
        "opportunist, opportunistic",
        "peremptory",
        "presumptuous",
        "recalcitrant",
        "self-righteous",
        "self-serving",
        "supercilious",
        "unabashed",
        "wayward",
        "bog",
        "coalesce",
        "confluence",
        "disseminate",
        "effervesce",
        "elicit",
        "indigenous",
        "induce",
        "inert, inertia",
        "inherent",
        "multifarious",
        "precipitate",
        "abate",
        "allocate",
        "atrophy",
        "attenuate",
        "burgeon",
        "circumscribe",
        "copious",
        "dearth",
        "devoid",
        "diffuse",
        "diminutive, diminution",
        "efface(ment)",
        "encompass",
        "encroaching",
        "excavate",
        "extricate",
        "gargantuan",
        
        "germinate",
        "hamper (verb)",
        "incubate",
        "indiscriminate",
        "inhibit(ing)",
        "innate",
        "innocuous",
        "insular(ity)",
        "inundate",
        "latent, latency",
        "mitigate, mitigator",
        "modicum",
        "motley",
        "parch",
        "paucity",
        "peripheral",
        "plasticity",
        "plethora, plethoric",
        "pliable, pliant",
        "preclude",
        "prodigious",
        "profuse, profusion",
        "prohibitive, prohibition",
        "proliferate, proliferation",
        "prolific",
        "quell",
        "rampant",
        "ravenous",
        "reap",
        "recessive",
        "relegate",
        "relinquish",
        "repertory",
        "satiate",
        "saturate",
        "scanty",
        "scope",
        "superfluous",
        "surfeit",
        "teem, teeming",
        "trifling",
        "ubiquitous",
        "vacuous, vacuity",
        "viscous",
        
        "waning",
        "byzantine",
        "cacophonous, cacophony",
        "cursory",
        "gait",
        "garish",
        "glutton(ous)",
        "lurid",
        "malleable",
        "ramshackle",
        "redolent",
        "shroud",
        "stark(ness)",
        "succulent",
        "antediluvian",
        "dilatory",
        "ephemeral",
        "hasten",
        "oracle",
        "prospective",
        "regressive",
        "sporadic",
        "temporize",
        "transient",
        "arcane",
        "belie",
        "charlatan",
        "circuitous",
        "clandestine",
        "demystify",
        "disingenuous",
        "divulge",
        "dupe",
        "duplicitous, duplicity",
        "enigma(tic)",
        "exposé",
        "fallacious",
        "fallacy",
        "fraudulent",
        "furtive",
        "incredulous, incredulity",
        "indeterminate",
        "inscrutable",
        
        "ostensible",
        "plausible, plausibility",
        "pretext",
        "prevaricator",
        "rectify, rectitude",
        "refutation, refute",
        "sanctimonious",
        "sophistry",
        "spurious",
        "substantiate",
        "auspicious",
        "barrage",
        "belligerent",
        "blighted",
        "bolster",
        "buttress",
        "circumvent",
        "conflagration",
        "contentious",
        "decimate",
        "deleterious",
        "depravity",
        "dire",
        "divergent",
        "divisive",
        "elude",
        "elusive",
        "embitter(ed)",
        "encumbrance",
        "fortuitous",
        "marred",
        "nefarious",
        "palliate, palliative",
        "precarious",
        "raze",
        "serendipity",
        "spartan",
        "vanquish",
        "vigilant",
        "vindictive",
        "virulent"
    ]
    
    static var definitions = [
        "seek (past tense)",
        "percieve or recognize",
        "unexplainable",
        "sluggish, inert, inactive",
        "peaceful",
        "вязкий",
        "calm",
        "able to recover",
        "окальцевать",
        "not notice",
        "can be achieved",
        "to push into action",
        "something that motivates",
        "provide more details",
        "friendly",
        "mixed feelings",
        
        "expectation",
        "the quality of being reticent; reserve",
        "anxiety or understanding",
        "созерцание",
        "shy or modest(lack of self-confidence)",
        "viewpoint",
        "почтить память",
        
        "scorn - contempt",
        "steadfast",
        "colossal",
        "boaster",
        "pointless",
        "about to happen",
        "illegal",
        "fail to be grasped",
        "scrape by",
        "helpful",
        "united",
        "tempt",
        "annoy",
        "easily managed",
        "highest point - acme  - apex",
        "resist",
        "prevent",
        "fully",
        "swindle - deceived",
        "straightforward",
        "increase",
        "hopeless",
        "make one lose confidence",
        "enthusiastic",
        "occasional",
        "non-religious",
        
        "difficult to understand",
        "appropriate, inclined",
        "coax",
        "succinct",
        "agree",
        "list, explain",
        "stray from the subject at hand",
        "clarify",
        "involve in an argument or conflict",
        "based on observation and experiment (not theory)",
        "list",
        "representative example",
        "ambiguous",
        "representative example",
        "encourage",
        "useful",
        "understand",
        "evident, obvious",
        "flushed, flowery",
        "inappropriateness, discrepancy",
        "impossible to express in words",
        "implicit suggestion",
        "concise",
        "clear, easily understood",
        "vague",
        "subtle difference",
        "clear example",
        "babble",
        "formal declaration",
        "supporter",
        "lacking imagination, dull",
        
        "defense, counterargument",
        "reject",
        "reject",
        "annul, retract",
        "(related to) elegant speech/writing, elegant speaker/writer",
        "examine carefully",
        "comparison",
        "digressive, irrelevant",
        "extensive written argument about some topic",
        "wordy, long-winded",
        "air, feeling",
        "pompous",
        "cheerful, floating",
        "insensitive",
        "irritable",
        "fickle",
        "bitter",
        "sociable, lively",
        "openly emotional",
        "sad, depressed",
        "shy",
        "disappointed, defeated",
        "disenchantment, disappointment",
        "unemotional",
        "joyful",
        "bring about, stir up",
        "well-suited, happy",
        "sad",
        "courage",
        "commotion, anger",
        "excessively dramatic or emotional",
        "simply tranquil",
        "rash, passionate",
        "angry",
        "tired, bored",
        "cheerful",
        "cheerful",
        "overly sentimental",
        "bleak",
        "fickle",
        "depressed",
        "unpleasant",
        "preference",
        "done routinely with little interest or care",
        "irritable",
        
        "intense, significant",
        "inclination, tendency",
        "offensive, disgusting",
        "emotionally reserved",
        "cheerfully confident, optimistic",
        "comfort, consolation",
        "bleak",
        "moody",
        "apprehension",
        "aggressive, bad-tempered",
        "felt indirectly by imagining someone else's experiences",
        "anger",
        "eagerness",
        "inactive",
        "enthusiastic",
        "calmness",
        "robust, sturdy",
        "lazy",
        "dull, boring",
        "provoke, start",
        "call forth, appeal to",
        "lacking energy, lethargic",
        "lazy person",
        "inactive, dreamy",
        "languid, sluggish",
        "short period of calm",
        "soothe, calm",
        "calm someone down",
        "calm",
        "harsh, rowdy",
        "provoke, excite",
        "lively, effervescent",
        "not moving",
        "not moving",
        "drowsiness, apathy",
        "boisterous, unrestrained",
        "dull, uninteresting",
        "hatred",
        "bitter animosity",
        "friendly",
        "dislike",
        "pleasant",
        "quarrelsome",
        
        "alienate, alienation",
        "demanding, severe requirements",
        "friendly",
        "meddlesome, interfering",
        "bitter resentment",
        "relationship",
        "hermit",
        "expressing care or concern, often too much",
        "unintentional",
        "yielding",
        "strive for",
        "diligent",
        "relieve, appease",
        "yielding",
        "courageous",
        "failure",
        "weaken(ed)",
        "respectful submission, yielding",
        "hindrance, impediment",
        "discouraging",
        "to drive away or disprove",
        "(causing) anxiety",
        "superficial, effortless",
        "hopeless",
        "courageous",
        "obstacle",
        "too strong to be defeated",
        "courageous",
        "difficult, trying",
        "submissive, subservient",
        "not yielding",
        "yielding",
        "stubborn, determined",
        "insignificant, flimsy",
        "suffering",
        "striving",
        "insightfulness",
        
        "skillful",
        "skillful",
        "study of human beings",
        "crude",
        "intellectual",
        "vulgar, boorish",
        "careful",
        "sophisticated, urbane",
        "the trait of trusting others too much",
        "(often excessively) morally instructive",
        "perceive, perceptive",
        "sudden realization",
        "scholarly",
        "understood only by a few",
        "careful",
        "tact, elegant skill",
        "confuse",
        "foolishness",
        "recklessly daring",
        "pompous, pretentious",
        "senseless, stupid",
        "incompetence",
        "unsophisticated and trusting, naive",
        "graceful, supple",
        "beginner",
        "mistake",
        "careful",
        "a person who makes a great show of his knowledge",
        "early development in maturity and intelligence",
        "narrow-minded, unsophisticated",
        "meticulous, attentive to detail",
        "a knowledgeable commentator",
        "foolish",
        "wise",
        "very careful and precise",
        "astute, smart",
        "careless, sloppy",
        "bewilder",
        "easily influenced or affected",
        "easily managed or controlled",
        "extraordinary, weird",
        "crude",
        "incomprehensible, unbelievable",
        
        "clumsy",
        "elegant, sophisticated",
        "commanding respect because of age, dignity",
        "one with exceptional musical skill",
        "clever or grim sense of humor",
        "strengthen or support with additional evidence",
        "order, politeness",
        "even-handed",
        "illegal",
        "accuse someone of a crime",
        "formally accuse of a crime",
        "angered (by injustice)",
        "lenient",
        "fair",
        "approve, confirm",
        "formally approve",
        "clear of blame or suspicion",
        "generous",
        "greed",
        "generous",
        "hand down (through a will)",
        "decrease in value",
        "poor",
        "too expensive",
        "cheap(ness)",
        "profitable",
        "lush, elaborate",
        "generosity, generous",
        "motivated by money",
        "cheap, stingy",
        "financially support, be condescending towards",
        "cheap, stingy",
        "additional payment, bonus",
        "get or provide",
        "prudent, frugal",
        "waste",
        "willing to accept bribes",
        "career",
        "deviation, not normal",
        "confront",
        
        "not yielding",
        "influence, domination",
        "one who practices self-denial as a spiritual discipline",
        "dignified",
        "dictator, dictatorial",
        "a person who acts like a robot",
        "common",
        "supported by two opposing groups (political parties)",
        "dethrone, remove from power",
        "not original",
        "violate the sacredness of",
        "dictator",
        "religious, political, or philosophical principles or teachings",
        "tending to force one's own opinions on other people",
        "from diverse sources",
        "belief in equality",
        "deliberately behaving a certain way to attract attention",
        "group within a larger group",
        "excessive enthusiasm",
        "common",
        "belief contrary to the established opinion",
        "unique personal trait, quirky",
        "conservative, traditional",
        "one who completely opposes violence",
        "someone with biased beliefs",
        "religious devotion",
        "controversial",
        "reject",
        "respectful, pious",
        "holiness",
        "strong and loyal",
        "standard, hackneyed",
        "loud and harsh",
        "one who intends to overthrow the government",
        "to take the place of",
        "suck up, flatterer",
        "suck-up",
        "undemocratic, rigid political control",
        
        "common",
        "seize power without authority",
        "fanatic",
        "belittle",
        "scold harshly",
        "belittle",
        "harshly critical",
        "scold",
        "belittle",
        "belittle",
        "dismay",
        "disdainful",
        "despicable",
        "blameworthy",
        "belittle",
        "disapprove, belittle",
        "make fun of",
        "disregard",
        "belittle",
        "praising speech",
        "praise",
        "praise",
        "poisonous",
        "blameworthy",
        "belittle",
        "scold",
        "harshly critical",
        "insult, snub",
        "reject with contempt",
        "critical speech",
        "praise",
        "haughty",
        "mortification",
        "self-satisfaction, smugness",
        "compromising, apologizing",
        "humiliation",
        "overly modest",
        "disrespectful",
        "arrogance",
        "dishonor, humiliation",
        "arrogant",
        "disrespectful, insolent",
        
        "disrespectful",
        "disrespectful",
        "infamous, ill fame",
        "stubborn",
        "stubborn(ness)",
        "a person who takes advantage of opportunities, often unethically",
        "bossy, decisive",
        "too bold, arrogant",
        "stubborn",
        "smug, holier-than-thou",
        "selfish",
        "arrogant",
        "not embarrassed",
        "selfish, stubborn",
        "marsh, swamp",
        "blend, fuse",
        "a place where things merge or flow together",
        "scatter widely",
        "bubble, fizz",
        "bring about",
        "native to a region",
        "cause",
        "not moving or active",
        "intrinsic, natural",
        "many types",
        "outcome",
        "lessen",
        "assign, portion",
        "waste away",
        "weaken, reduce",
        "grow, flourish",
        "restrict",
        "abundant",
        "scarcity",
        "lacking",
        "spread out",
        "extremely small",
        "erase",
        "include, surround",
        "intrusive",
        "unearth, dig up",
        "disentangle",
        "gigantic",
        
        "(cause to) grow",
        "hinder, restrict",
        "develop, grow",
        "unselective, random",
        "restrain(ing)",
        "intrinsic, natural",
        "harmless",
        "related to or similar to an island",
        "flood",
        "the state of being not yet evident or active",
        "moderate, alleviate",
        "small amount",
        "diverse, heterogeneous",
        "make dry",
        "scarcity",
        "outermost, secondary",
        "malleability, the ability to be shaped or molded",
        "surplus",
        "easily shaped or influenced",
        "prevent",
        "huge",
        "plentiful",
        "restrictive",
        "grow, increase",
        "fertile, fruitful",
        "suppress, quench",
        "unrestrained, growing",
        "insatiable, having a huge appetite",
        "harvest, gather",
        "tending to go backward",
        "demote",
        "give back",
        "collection",
        "satisfy fully",
        "flood, soak",
        "barely sufficient",
        "opportunity, range",
        "more than necessary",
        "surplus",
        "abundant",
        "frivolous, unimportant",
        "ever-present, pervasive",
        "empty",
        "thick, sticky",
        
        "lessening",
        "convoluted, complex",
        "discordant sound",
        "hasty, superficial",
        "manner of walking",
        "tastelessly showy",
        "someone who eats and drinks too much",
        "sensational, shocking",
        "capable of being shaped, pliable",
        "poorly constructed",
        "reminiscent, having smell",
        "hide, obscure",
        "harsh, plain",
        "delicious",
        "very old",
        "tending to waste time",
        "short-lived",
        "speed up the progress of",
        "prophet",
        "likely or expected to become",
        "tending to return or revert",
        "occurring at irregular intervals",
        "delay, evade",
        "lasting for only a short time",
        "mysterious, known only by a few",
        "give a false impression",
        "swindler",
        "indirect",
        "secretive",
        "make clear and comprehensible",
        "insincere",
        "make known",
        "deceive",
        "deliberately deceptive",
        "mystery, mysterious",
        "a report designed to reveal the truth to the public",
        "deceitful, incorrect",
        "false belief",
        "deceitful",
        "sneaky",
        "skeptical",
        "left doubtful, inconclusive",
        "mysterious",
        
        "apparent, seeming",
        "likely true",
        "misleading claim or appearance",
        "liar",
        "put right, correct",
        "arguing that a claim is false",
        "pretending to be religious, hypocritical",
        "deceptive reasoning",
        "false, inauthentic",
        "confirm, establish as genuine",
        "favorable",
        "bombardment, torrent",
        "aggressive, warlike",
        "destroyed",
        "support",
        "support",
        "escape, avoid",
        "large destructive fire",
        "belligerent, quarrelsome",
        "destroy",
        "harmful",
        "moral corruption",
        "urgent, dreadful",
        "different, conflicting",
        "creating conflict",
        "evade",
        "difficulty to catch or define",
        "make worse",
        "burden",
        "fortunate, lucky",
        "scarred",
        "evil",
        "relieve pain without curing",
        "dangerous, unstable",
        "destroy, demolish",
        "luck",
        "simple, self-disciplined",
        "conquer, defeat",
        "watchful, alert",
        "seeking revenge",
        "poisonous"
    ]
}
